import { Router } from "express";


import userRoutes from "./userRoutes";
import authRoutes from "./authRoutes";

import settingRoutes from "./settingRoutes";
import contactRoutes from "./contactRoutes";
import ticketRoutes from "./ticketRoutes";
import whatsappRoutes from "./whatsappRoutes";
import apiRoutes from "./apiRoutes";
import satisfactionSurveyRoutes from './satisfactionSurveyRoutes';
import messageRoutes from "./messageRoutes";
import whatsappSessionRoutes from "./whatsappSessionRoutes";
import queueRoutes from "./queueRoutes";
import companyRoutes from "./companyRoutes";
import planRoutes from "./planRoutes";
import ticketNoteRoutes from "./ticketNoteRoutes";
import quickMessageRoutes from "./quickMessageRoutes";
import helpRoutes from "./helpRoutes";
import dashboardRoutes from "./dashboardRoutes";
import zdashboardRoutes from "./zdashboardRoutes";
import featureRoutes from "./featureRoutes";
import assistantRoutes from "./assistantRoutes";
import queueOptionRoutes from "./queueOptionRoutes";
import scheduleRoutes from "./scheduleRoutes";
import tagRoutes from "./tagRoutes";
import contactListRoutes from "./contactListRoutes";
import contactListItemRoutes from "./contactListItemRoutes";
import healthCheckRoutes from "./healthCheckRoutes";
import campaignRoutes from "./campaignRoutes";
import campaignSettingRoutes from "./campaignSettingRoutes";
import announcementRoutes from "./announcementRoutes";
import agendamentoRoutes from "./agendamentoRoutes";
import chatRoutes from "./chatRoutes";
import invoiceRoutes from "./invoicesRoutes";
import subscriptionRoutes from "./subScriptionRoutes";
import ticketTagRoutes from "./ticketTagRoutes";
import filesRoutes from "./filesRoutes";
import promptRoutes from "./promptRouter";
import queueIntegrationRoutes from "./queueIntegrationRoutes";
import emailRoutes from "./emailRoutes";
import taskChargeRoutes from "./taskChargeRoutes";
import taskSubjectRoutes from "./taskSubjectRoutes";
import taskReportRoutes from "./taskReportRoutes";
import taskRoutes from "./taskRoutes";
import versionRouter from "./versionRoutes";
import reportRoutes from "./reportRoutes";
import reasonRoutes from "./reasonRoutes";
import glpiRoutes from "./GLPIRoutes";
import superUtils from "./superUtils";
import employerRoutes from "./employerRoutes";
import positionRoutes from "./positionRoutes";
import statistics from "./statisticsRoutes";
import kanbanRoutes from "./kanbanRoutes";
import queueTagRoutes from "./queueTagRoutes";
import adminDashboardRoutes from "./adminDashboardRoutes";
import contactImportExportRoutes from "./contactImportExportRoutes";
import passwordRoutes from "./passwordRoutes";
import groupRoutes from "./groupRoutes";
import contactTagsRoutes from "./contactTagRoutes";
import messageRuleRoutes from "./messageRuleRoutes";
import flowBuilderRoutes from "./flowBuilderRoutes";
import horarioRoutes from "./horarioRoutes";
import voiceRoutes from "./voiceRoutes";
import performanceRoutes from "./performanceRoutes"; 

const routes = Router();

routes.use(apiRoutes);
routes.use(performanceRoutes);
routes.use(userRoutes);
routes.use(healthCheckRoutes);
routes.use(adminDashboardRoutes);
routes.use("/auth", authRoutes);
routes.use(superUtils);
routes.use("/statistics", statistics);
routes.use(agendamentoRoutes);
routes.use(taskChargeRoutes);
routes.use(taskReportRoutes);
routes.use(taskSubjectRoutes);
routes.use(settingRoutes);
routes.use(assistantRoutes);
routes.use(kanbanRoutes);
routes.use(featureRoutes);
routes.use(contactRoutes);
routes.use(contactImportExportRoutes);
routes.use(employerRoutes);
routes.use(passwordRoutes);
routes.use(satisfactionSurveyRoutes);
routes.use(positionRoutes);
routes.use(assistantRoutes);
routes.use(ticketRoutes);
routes.use(whatsappRoutes);
routes.use(contactTagsRoutes);
routes.use(messageRoutes);
routes.use(whatsappSessionRoutes);
routes.use(groupRoutes);
routes.use(queueRoutes);
routes.use(companyRoutes);
routes.use(planRoutes);
routes.use(ticketNoteRoutes);
routes.use(quickMessageRoutes);
routes.use(helpRoutes);
routes.use(dashboardRoutes);
routes.use(zdashboardRoutes);
routes.use(queueOptionRoutes);
routes.use(scheduleRoutes);
routes.use(tagRoutes);
routes.use(contactListRoutes);
routes.use(contactListItemRoutes);
routes.use(campaignRoutes);
routes.use(campaignSettingRoutes);
routes.use(announcementRoutes);
routes.use(messageRuleRoutes);
routes.use(reportRoutes);
routes.use(chatRoutes);
routes.use(subscriptionRoutes);
routes.use(invoiceRoutes);
routes.use(ticketTagRoutes);
routes.use(filesRoutes);
routes.use(promptRoutes);
routes.use(queueIntegrationRoutes);
routes.use(emailRoutes);
routes.use(queueTagRoutes);
routes.use(taskRoutes);
routes.use(versionRouter);
routes.use(reasonRoutes);
routes.use(glpiRoutes);
routes.use(flowBuilderRoutes);
routes.use(taskRoutes);
routes.use(horarioRoutes);
routes.use(voiceRoutes);


export default routes;
