const rules = {
	user: {
	  static: [
		"user-modal:editPassword",
		"connections-page:restartConnection",
		"ticket-options:spy",
		"ticket-options:reject",
		"ticket-options:transferTicket",
		"contacts-page:createContact",
		"contacts-page:deleteContact",
		"contacts-page:editContact",
		"tasks-page:viewOwn",
		"tasks-page:editOwn",
		// Permissões básicas para grupos
		"groups:view",
		"groups:join"
	  ],
	},
  
	superv: {
	  static: [
		"dashboard:view",
		"drawer-superv-items:view",
		"tickets-manager:showall",
		"user-modal:editWhatsApp",
		"user-modal:editDetails",
		"user-modal:editPassword",
		"user-modal:editQueues",
		"user-modal:editSpy",
		"user-modal:editIsTricked",
		"user-modal:editViewAllTicket",
		"ticket-options:transferTicket",
		"ticket-options:deleteTicket",
		"ticket-options:spy",
		"ticket-options:reject",
		"users-page:deleteUser",
		"connections-page:restartConnection",
		"tasks-page:viewSupervised",
		"tasks-page:editSupervised",
		"tasks-page:deleteSupervised",
		"tasks-page:manageCategories",
		"contacts-page:createContact",
		"contacts-page:deleteContact",
		"contacts-page:editContact",
		"contacts-page:importExport",
		"contacts-page:groupsTools",
		"contacts-page:blockContact",
		"contacts-page:deleteAllContacts",
		"connections-page:restartConnection",
		"users-page:deleteUser",
		// Permissões adicionais para grupos
		"groups:view",
		"groups:create",
		"groups:edit",
		"groups:delete",
		"groups:join",
		"groups:manageParticipants",
		"groups:manageRequests"
	  ],
	},
  
	admin: {
	  static: [
		"dashboard:view",
		"dashboard-admin:view",
		"drawer-admin-items:view",
		"tickets-manager:showall",
		"user-modal:editProfile",
		"user-modal:editWhatsApp",
		"user-modal:editDetails",
		"user-modal:editPassword",
		"user-modal:editQueues",
		"user-modal:editSpy",
		"user-modal:editIsTricked",
		"user-modal:editViewAllTicket",
		"ticket-options:transferTicket",
		"ticket-options:deleteTicket",
		"ticket-options:spy",
		"ticket-options:reject",
		"tags-page:view",
		"tags-page:addTag",
		"tags-page:delTag",
		"tags-page:editTag",
		"tasks-page:viewAll",
		"tasks-page:editAll",
		"tasks-page:deleteAll",
		"connections-page:restartConnection",
		"tasks-page:manageCategories",
		"contacts-page:createContact",
		"contacts-page:editContact",
		"contacts-page:deleteContact",
		"contacts-page:importExport",
		"contacts-page:groupsTools",
		"contacts-page:blockContact",
		"contacts-page:deleteAllContacts",
		"connections-page:actionButtons",
		"connections-page:addConnection",
		"connections-page:editOrDeleteConnection",
		"connections-page:restartConnection",
		"users-page:deleteUser",
		"metrics:view",
		"groups:view",
		"groups:create",
		"groups:edit",
		"groups:delete",
		"groups:join",
		"groups:manageParticipants",
		"groups:manageRequests",
		"groups:manageSettings"
	  ],
	},
  };
  
  export default rules;